language: ruby

rvm:
- 1.9.3
- 1.9.2
- ruby-head

env:
- "CHEF_VERSION=11.4.0"
- "CHEF_VERSION=10.24.0"
- "CHEF_VERSION=0.10.10"
- "CHEF_VERSION=0.9.18"
- "CHEF_HEAD=yes"

matrix:
  allow_failures:
  - rvm: ruby-head
