language: ruby

rvm:
- 2.0.0
- 1.9.3

env:
- "CHEF_VERSION=11.4.0"
- "CHEF_VERSION=10.24.0"
- "CHEF_VERSION=0.10.10"
- "CHEF_HEAD=yes"

matrix:
  exclude:
    - rvm: 2.0.0
      env: "CHEF_VERSION=0.9.18"
